version: '3'
services:
  db:
    image: postgres:13.3
    restart: always
    volumes:
      - .:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      
  service:
    build: app
    image: django
    volumes:
      - static_volume:/opt/app/static
      - media_volume:/opt/app/media
    ports:
      - "8000:8000"
    env_file:
      - ./app/example/.env
    depends_on:
      - db

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs:/etc/nginx/conf.d:ro
      - ./data:/data/:ro
      - static_volume:/opt/app/static
      - media_volume:/opt/app/media
    depends_on:
      - service
    ports:
      - "80:80"

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger_ui_container
    ports:
        - "8080:8080"
    volumes:
        - ./openapi.yaml:/swagger/openapi.yaml
    environment:
      SWAGGER_JSON: /swagger/openapi.yaml
  
volumes:
  static_volume:
  media_volume:
